include:
  - board: mwavenumpad
    snippet: studio-rpc-usb-uart  
  - board: mwavenumpad
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y
    artifact-name: settings-reset